version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
    networks:
      - ml_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8999:8999"
    volumes:
      - .:/app
    networks:
      - ml_network
    depends_on:
      - mlflow

networks:
  ml_network:
    driver: bridge 